config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :user_profile

  resources :projects
  resources :sprints, except: [:index]
  resources :activities, except: [:index]
  resources :colors, except: [:show]
  resources :labels, except: [:show]
  resources :statuses, except: [:show]
  resources :macro_activities, except: [:index, :show]
  resources :progresses, except: [:show]
  get '/progresses/report_pdf', to: 'progresses#report_pdf', as: 'progress_report_pdf'
  resources :weeks, only: [:edit, :update]

  post '/projects/:id/login', to: 'hours_registries#login', as: 'project_login'
  put '/projects/:id/logout', to: 'hours_registries#logout', as: 'project_logout'

  get 'progresses/graphic' => 'progresses#graphic'

  post 'team_users/edit_multiple'
  put 'team_users/update_multiple'

  get 'home/index'
  root 'home#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

  # Associations
  belongs_to :team

  has_many :activities, dependent: :destroy
  has_many :project_sprints, dependent: :destroy
  has_many :sprints, through: :project_sprints

  has_many :macro_activities, dependent: :destroy
  has_many :progresses, dependent: :destroy

  has_many :hours_registries, dependent: :destroy


  # Validations
  validates_presence_of :description, :team_id

  # Nested Attributes
  accepts_nested_attributes_for :progresses, allow_destroy: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # Erro da gem Cancan (ActiveModel::ForbiddenAttributesError)
  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  load_and_authorize_resource

  def index
    if current_user_total?
      @projects = Project.all.order(:description).page(params[:page]).per(10)
    else
      ids = []
      tus = TeamUser.where(user_id: current_user.id)
      tus.each do |tu|
        ids << tu.team_id
      end

      @projects = Project.where(team_id: ids).order(:description)
                  .page(params[:page]).per(10)
    end
  end

  def show
    @project = Project.find(params[:id])
    @sprints = @project.sprints
  end

   def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save

      @sprints = Sprint.where(id: params[:sprint_ids])

      if @sprints.present?
        @sprints.each do |sprint|
          project_sprint = ProjectSprint.new
          project_sprint.project_id = @project.id
          project_sprint.sprint_id = sprint.id
          project_sprint.save
        end
      end

      redirect_to project_path(@project), notice: "Projeto criado com sucesso!"

    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @sprints = Sprint.where(id: params[:sprint_ids]).ids

    # Atualização das sprints do projeto [ProjectSprint]
    @project.project_sprints.each do |project_sprint|
      @id = @sprints.sample

      if @id.blank?
        project_sprint.destroy
      else
        project_sprint.update_attribute('sprint_id', @id)
      end
      @sprints.delete(@id)
    end

    unless @sprints.blank?
      @sprints.each do |sprint|
        ProjectSprint.create!(
          project_id: @project.id,
          sprint_id: sprint
          )
      end
    end

    # Atualização dos progressos do projeto
    @project.progresses.each do |p|
      p.advance = @project.progresses.where('id < ?', p.id).present? ?
                  p.completeness.to_i - @project.progresses
                                        .where('id < ?', p.id).last
                                        .completeness.to_i :
                  p.completeness
      p.save!
    end

    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Projeto atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path, notice: "Projeto deletado com sucesso!"
    else
      redirect_to projects_path, notice: "Erro ao deletar o Project..."
    end
  end

  private

  def project_params
    params.require(:project).permit(:id, :description, :team_id,
                                    progresses_attributes:
                                    [:id, :completeness, :advance,
                                     :_destroy])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/shared/_macro_activities_list.html.erb
<hr style="border-top-color: dimgray;">
<span class="title">Macro Atividades:</span> <br><br>

<table class="table table-striped table-hover ">

  <thead>
    <tr>

      <th>Descrição</th>
      <th>Completude atual (%)</th>
      <% if current_user_total? %>
        <th colspan="2"></th>
      <% end %>

    </tr>
  </thead>

  <tbody>
    <% @project.macro_activities.each do |ma| %>
      <tr>

        <td>
          <%= ma.description %>
        </td>

        <td>
          <%= ma.completeness.present? ? ma.completeness : '0' %>
        </td>

        <% if can? :update, MacroActivity %>
          <td width="100">
            <%= link_to t('buttons.edit'), edit_macro_activity_path(ma) %>
          </td>
        <% end %>

        <% if can? :destroy, MacroActivity %>
          <td width="100">
            <%= link_to t('buttons.destroy'), macro_activity_path(ma), method: :delete, data: { confirm: t('messages.confirm') } %>
          </td>
        <% end %>

      </tr>
    <% end %>
  </tbody>

</table>

<% if can? :create, MacroActivity %>
  <%= link_to "Novo", new_macro_activity_path(project: @project), class: 'btn btn-primary' %>
  <br><br>
<% end %>

app/views/projects/shared/_select_sprints.html.erb
<div class="form-group">
  <%= hidden_field_tag  "sprint_ids[]" %>

  <div class="col-lg-6 col-lg-offset-2">
    <%= select(nil, "sprint_ids[]",
               Sprint.all.collect {|s| [ truncate(s.description, length: 55), s.id ] },
               {include_blank: '-- Selecione um sprint --'},
               {onchange: 'sprint_ids(this)', class: "form-control"}) %>
  </div>

  <div class="col-lg-2">
    <a onclick='removeSelect(this)' class="btn btn-default">Remover</a>
  </div>

</div>

<span id="add"></span>

app/views/projects/shared/_sprints_list.html.erb
<hr style="border-top-color: dimgray;">
<span class="title">Sprints:</span> <br><br>

<table class="table table-striped table-hover ">

  <thead>
    <tr>

      <th>Descrição</th>
      <th>Semestre</th>
      <th>Qtd. atividades</th>
      <th>Pontos planejados</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @sprints.order(:semester).each do |sprint| %>
      <tr <%= "class=current_period" if Date.today.between?(sprint.inicio, sprint.fim) %>>

        <td>
          <%= sprint.description %>
        </td>

        <td>
          <%= sprint.semester %>
        </td>

        <td>
          <% activities = 0 %>
          <% sprint.activities.each do |activity| %>
            <% if current_user_total? %>
              <% activities += 1 if activity.project_id == @project.id %>
            <% else %>
              <% if activity.project_id == @project.id &&
                    activity.user_id == current_user.id %>
                <% activities += 1 %>
              <% end %>
            <% end %>
          <% end %>

          <%= activities %>
        </td>


        <td>
          <% pontos_cadastrados = 0 %>
          <% sprint.activities.each do |activity| %>

            <% if current_user_total? %>

              <% if activity.project_id == @project.id %>
                <% pontos_cadastrados += activity.pontos_cadastrados %>
              <% end %>

            <% else %>

              <% if activity.project_id == @project.id &&
                    activity.user_id == current_user.id %>
                <% pontos_cadastrados += activity.pontos_cadastrados %>
              <% end %>

            <% end %>

          <% end %>

          <%= pontos_cadastrados %>
        </td>

        <td align="center">
          <%= link_to "Visualizar", sprint_path(sprint, project: @project) %>
        </td>

        <% if can? :update, Sprint %>
          <td width="100" align="center">
            <%= link_to t('buttons.edit'), edit_sprint_path(sprint, project: @project) %>
          </td>
        <% end %>

        <% if can? :destroy, Sprint %>
          <td width="100" align="center">
            <%= link_to t('buttons.destroy'), sprint_path(sprint, project: @project), method: :delete, data: { confirm: t('messages.confirm') } %>
          </td>
        <% end %>

      </tr>
    <% end %>
  </tbody>

</table>

<% if current_user_total? %>
  <% if can? :create, Sprint %>
    <%= link_to "Nova Sprint", new_sprint_path(project: @project), class: "btn btn-primary" %> |
    <%= link_to "Nova Atividade", new_activity_path(project: @project), class: "btn btn-warning" %>
  <% end %>
<% else %>
  <%= link_to "Nova Atividade", new_activity_path(project: @project), class: "btn btn-primary" %>
<% end %>