config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :user_profile

  resources :projects
  resources :sprints, except: [:index]
  resources :activities, except: [:index]
  resources :colors, except: [:show]
  resources :labels, except: [:show]
  resources :statuses, except: [:show]
  resources :macro_activities, except: [:index, :show]
  resources :progresses, except: [:show]
  get '/progresses/report_pdf', to: 'progresses#report_pdf', as: 'progress_report_pdf'
  resources :weeks, only: [:edit, :update]

  post '/projects/:id/login', to: 'hours_registries#login', as: 'project_login'
  put '/projects/:id/logout', to: 'hours_registries#logout', as: 'project_logout'

  get 'progresses/graphic' => 'progresses#graphic'

  post 'team_users/edit_multiple'
  put 'team_users/update_multiple'

  get 'home/index'
  root 'home#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    if user.user_profile.role == "Total"
      can :manage, :all
    else
      can [:read, :update], UserProfile, id: user.id
      # can :update, UserProfile, id: user.id
      can :read, Team
      can :read, Project
      can :read, MacroActivity
      can :read, Sprint
      can :manage, Activity
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :status
  belongs_to :label
  belongs_to :sprint
  belongs_to :project
  belongs_to :user

  validates_presence_of :description, :project_id, :sprint_id, :user_id
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :label, dependent: :nullify
  has_many :status, dependent: :nullify
end

app/models/hours_registry.rb
class HoursRegistry < ApplicationRecord
  belongs_to :week
  belongs_to :user
  belongs_to :project
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :color
  has_many :activities, dependent: :nullify
end

app/models/macro_activity.rb
class MacroActivity < ApplicationRecord

  # Associations
  belongs_to :project

  # Validations
  validates_presence_of :description, :project_id
end

app/models/progress.rb
class Progress < ApplicationRecord
  belongs_to :project
  belongs_to :sprint

  validates_presence_of :completeness, :project_id, :sprint_id
end

app/models/project.rb
class Project < ApplicationRecord

  # Associations
  belongs_to :team

  has_many :activities, dependent: :destroy
  has_many :project_sprints, dependent: :destroy
  has_many :sprints, through: :project_sprints

  has_many :macro_activities, dependent: :destroy
  has_many :progresses, dependent: :destroy

  has_many :hours_registries, dependent: :destroy


  # Validations
  validates_presence_of :description, :team_id

  # Nested Attributes
  accepts_nested_attributes_for :progresses, allow_destroy: true
end

app/models/report_pdf.rb
class ReportPdf

  def initialize(report)
    @report = report
  end

  def to_pdf
    kit = WickedPdf.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/report.pdf")
  end

  def filename
    "report #{report.id}.pdf"
  end

  private

    attr_reader :report

    def as_html
      render template: "reports/pdf", layout: "report_pdf",
             locals: { :@project => report }
    end
end

app/models/sprint.rb
class Sprint < ApplicationRecord

  # Associations
  has_many :project_sprints, dependent: :destroy
  has_many :projects, through: :project_sprints
  has_many :activities, dependent: :destroy
  has_many :progresses, dependent: :destroy
  has_many :weeks, dependent: :destroy

  # Validations
  validates_presence_of :description, :semester, :inicio, :fim
  validate :inicio_is_date?

  private

  def inicio_is_date?
    if !inicio.is_a?(Date)
      errors.add(:inicio, 'não é uma data válida')
    end
  end
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :color
  has_many :activities, dependent: :nullify
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users, dependent: :destroy
  has_many :users, through: :team_users
  has_one :project, dependent: :destroy # adicionado

  #has_and_belongs_to_many :users
  validates_presence_of :description
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_one :user_profile, dependent: :destroy
  has_many :team_users, dependent: :destroy
  has_many :teams, through: :team_users
  has_many :activities, dependent: :destroy
  has_many :hours_registries, dependent: :destroy

  # Validations
  validates_presence_of :email, :password, :password_confirmation
  validates_confirmation_of :password
  validates_format_of :email, with: EMAIL_REGEXP


  # Nested Attributes
  accepts_nested_attributes_for :user_profile, allow_destroy: true # formulario alinhado (ser_profile+user)

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  # Associations
  enum role: { :Total => 0, :Parcial => 1 }
  belongs_to :user, optional: true

  validates_presence_of :name, :student_number
  validates_length_of :student_number, maximum: 10, allow_blank: false

  #paperclip
  # "#" instead ">": cut from the middle
  has_attached_file :picture, #styles: { medium: '300x300#', thumb: '100x100#' },
                    default_url: "usuario_padrao.png" #configura tamanho da imagem e se nao tiver, gera a imagem padrao
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/ #aceeita qlq tipo de imagem

end

app/models/users_team.rb
class UsersTeam < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :sprint
  has_many :hours_registries, dependent: :destroy

  accepts_nested_attributes_for :hours_registries
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  before_action :set_label, only: [:edit, :update, :destroy]
  # Erro da gem Cancan (ActiveModel::ForbiddenAttributesError)
  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
  load_and_authorize_resource

  def index
    @labels = Label.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_path, notice: "Rótulo criada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path, notice: "Rótulo atualizada com sucesso!"
    else
      render :new
    end
  end

  def destroy
    if @label.destroy
      redirect_to labels_path, notice: "Rótulo excluída com sucesso!"
    end
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:id, :description, :color_id)
  end

end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/labels/edit.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Editar rótulo</center></h3>
      </div>
    </div>


    <div class="panel-body">
      <%= form_for(@label, html: {class: 'form-horizontal'}) do |f| %>

        <% if @label.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-dismissible alert-danger">
              <h5><%= "Existe(m) #{pluralize(@label.errors.count, 'erro(s)')} no formulário:" %></h5>
            <ul>
            <% @label.errors.full_messages.each do |message| %>
                <li><h6><%= message %></h6></li>
            <% end %>
            </ul>
            </div>
          </div>
          <br>
        <% end %>

        <div class="panel-body">
          <fieldset>

            <div class="form-group">
              <label class="col-lg-2 control-label">Descrição: </label>
              <div class="col-lg-8">
                <%= f.text_field :description, class: 'form-control', onchange: 'viewLabelText(this)' %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Cor: </label>

              <div class="col-lg-8">

                <div class="col-lg-4" style="margin-left: -14px">
                  <%= f.select(:color_id,
                               Color.all.order(:description).collect {|c| [c.description, c.id ] },
                               {},
                               {class: "form-control",
                                onchange: 'viewLabelColor(this)'}) %>
                </div>

                <div class="col-lg-8">
                  <label class="col-lg-6 control-label">Pré-visualização: </label>
                  <span id="view-color" class="label label-default col-lg-6" style="margin-top: 12px; padding: 4px">
                    <%= @label.description %>
                  </span>
                </div>

              </div>
            </div>

            <br>

            <br>

          </fieldset>
        </div>

      <%= f.submit t('buttons.save'), class: "btn btn-primary" %> |
      <%= link_to t('buttons.back'), labels_path, class: "btn btn-success" %>

    </div>
  </div>

<% end %>

<script>
  $(document).ready(function($) {
    var select = $('#label_color_id')[0];
    var color = select.item(select.selectedIndex).text
    var span = $('#view-color')[0];
    span.style = 'margin-top: 12px;' + 'background-color: ' + color;
    var input = $('#label_description')[0];
    span.innerText = input.value;
  });
  function viewLabelColor(element) {
    var select = $(element)[0];
    var color = select.item(select.selectedIndex).text
    var span = $('#view-color')[0];
    span.style = 'margin-top: 10px; padding: 4px; background-color: ' + color;
  }
  function viewLabelText(element) {
    var input = $(element)[0];
    var span = $('#view-color')[0];
    span.innerText = input.value;
  }
</script>

app/views/labels/index.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Lista de rótulos</center></h3>
      </div>
    </div>

    <div class="panel-body">
      <table class="table table-striped table-hover ">

        <thead>
          <tr>
            <th>Descrição</th>
            <th>Cor</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @labels.each do |label| %>
            <tr>
              <td>
                <%= label.description %>
              </td>
              <td>
                <%#= label.color.blank? ? '-' : label.color.description %>
                <% if label.color.blank? %>
                  -
                <% else %>
                  <span class="color-description" style="background-color: <%= label.color.description %>"></span>
                  <%= label.color.description %>
                <% end %>
              </td>
              <td width="100" align="center">
                <%= link_to t('buttons.edit'), edit_label_path(label) %>
              </td>
              <td width="100" align="center">
                <%= link_to t('buttons.destroy'), label, method: :delete, data: { confirm: t('messages.confirm') } %>
              </td>
            </tr>
          <% end %>
        </tbody>

      </table>

      <center><%= paginate @labels %></center>

      <% if can? :create, Label %>
        <%= link_to t('buttons.new'), new_label_path, class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/labels/new.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Criar rótulo</center></h3>
      </div>
    </div>


    <div class="panel-body">
      <%= form_for(@label, html: {class: 'form-horizontal'}) do |f| %>

        <% if @label.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-dismissible alert-danger">
              <h5><%= "Existe(m) #{pluralize(@label.errors.count, 'erro(s)')} no formulário:" %></h5>
            <ul>
            <% @label.errors.full_messages.each do |message| %>
                <li><h6><%= message %></h6></li>
            <% end %>
            </ul>
            </div>
          </div>
          <br>
        <% end %>

        <div class="panel-body">
          <fieldset>

            <div class="form-group">
              <label class="col-lg-2 control-label">Descrição: </label>
              <div class="col-lg-8">
                <%= f.text_field :description, class: 'form-control', onchange: 'viewLabelText(this)' %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Cor: </label>

              <div class="col-lg-8">

                <div class="col-lg-4" style="margin-left: -14px">
                  <%= f.select(:color_id,
                               Color.all.order(:description).collect {|c| [c.description, c.id ] },
                               {},
                               {class: "form-control",
                                onchange: 'viewLabelColor(this)'}) %>
                </div>

                <div class="col-lg-8">
                  <label class="col-lg-6 control-label">Pré-visualização: </label>
                  <span id="view-color" class="label label-default col-lg-6" style="margin-top: 12px; padding: 4px;
                         background-color: <%= Color.order(:description).first.description %>">
                    Visualização do Rótulo
                  </span>
                </div>

              </div>
            </div>

            <br>

            <br>

          </fieldset>
        </div>

      <%= f.submit t('buttons.save'), class: "btn btn-primary" %> |
      <%= link_to t('buttons.back'), labels_path, class: "btn btn-success" %>

    </div>
  </div>

<% end %>

<script>
  function viewLabelColor(element) {
    var select = $(element)[0];
    var color = select.item(select.selectedIndex).text
    var span = $('#view-color')[0];
    span.style = 'margin-top: 10px; padding: 4px; background-color: ' + color;
  }
  function viewLabelText(element) {
    var input = $(element)[0];
    var span = $('#view-color')[0];
    span.innerText = input.value;
  }
</script>

app/views/labels/show.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Visualização do rótulo</center></h3>
      </div>
    </div>

    <div class="panel-body">
      <span class="title">Descrição:</span> <%= @label.description %> <br>
      <span class="title">Cor:</span> <%= @label.color.blank? ? '-' : @label.color.description %>

      <br><br><br>

      <% if can? :update, Label %>
        <%= link_to t('buttons.edit'), edit_label_path(@label), class: "btn btn-primary" %> |
      <% end %>
      <%= link_to t('buttons.back'), labels_path, class: "btn btn-success" %>

    </div>

  </div>
</div>