config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :user_profile

  resources :projects
  resources :sprints, except: [:index]
  resources :activities, except: [:index]
  resources :colors, except: [:show]
  resources :labels, except: [:show]
  resources :statuses, except: [:show]
  resources :macro_activities, except: [:index, :show]
  resources :progresses, except: [:show]
  get '/progresses/report_pdf', to: 'progresses#report_pdf', as: 'progress_report_pdf'
  resources :weeks, only: [:edit, :update]

  post '/projects/:id/login', to: 'hours_registries#login', as: 'project_login'
  put '/projects/:id/logout', to: 'hours_registries#logout', as: 'project_logout'

  get 'progresses/graphic' => 'progresses#graphic'

  post 'team_users/edit_multiple'
  put 'team_users/update_multiple'

  get 'home/index'
  root 'home#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sprint.rb
class Sprint < ApplicationRecord

  # Associations
  has_many :project_sprints, dependent: :destroy
  has_many :projects, through: :project_sprints
  has_many :activities, dependent: :destroy
  has_many :progresses, dependent: :destroy
  has_many :weeks, dependent: :destroy

  # Validations
  validates_presence_of :description, :semester, :inicio, :fim
  validate :inicio_is_date?

  private

  def inicio_is_date?
    if !inicio.is_a?(Date)
      errors.add(:inicio, 'não é uma data válida')
    end
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController

  include SprintsHelper

  # Erro da gem Cancan (ActiveModel::ForbiddenAttributesError)
  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
  load_and_authorize_resource

  def show
    @sprint = Sprint.find(params[:id]) #pega a variavel Sprint e o id especifico para mostrar os dados dela
    @project = Project.find(params[:project])
    @activities = Activity.all
                  .joins({user: :user_profile})
                  .where(project_id: @project.id, sprint_id: @sprint.id)
                  .order("user_profiles.name").page(params[:page]).per(10)
  end

  def new
    @sprint = Sprint.new
    @project = Project.find(params[:project]).id
  end

  def create

    @sprint = Sprint.new(sprint_params)

    verify_dates # Function - Verifica se não existe uma sprint nesse período

    unless @sprint.errors.any?

      if @sprint.save

        @project_sprint = ProjectSprint.new(project_id: params[:project],
                                            sprint_id: @sprint.id)

        if @project_sprint.save

          create_weeks_dynamically # Function - Cria as semanas dinamicamente

          redirect_to sprint_path(@sprint, project: params[:project]),
          notice: "Sprint criado com sucesso!"
        end

      end

    else
      render :new, locals: {:@project => params[:project].to_i}
    end

  end

  def edit
    @sprint = Sprint.find(params[:id]) #pega a variavel Sprint e o id especifico para editar os dados dela
    @project = Project.find(params[:project]).id
  end

  def update
    @sprint = Sprint.find(params[:id])
    @last_end = @sprint.fim

    verify_dates # Function - Verifica se não existe uma sprint nesse período

    unless @sprint.errors.any?

      if @sprint.update(sprint_params)

        update_weeks_dynamically(@last_end) # Function - Cria as semanas dinamicamente

        redirect_to sprint_path(@sprint, project: params[:project]),
        notice: "Sprint atualizado com sucesso!"
      end
    else
      render :edit, locals: {:@project => params[:project].to_i}
    end
  end

  def destroy
    @sprint = Sprint.find(params[:id])
    if @sprint.destroy
      redirect_to project_path(params[:project]), notice: "Sprint deletado com sucesso!"
    else
      redirect_to project_path(params[:project]), notice: "Erro ao deletar o Sprint..."
    end
  end


  private

  def sprint_params # Coloca os parametros que vao ser utilizados. Evita parametros indesejados
    params.require(:sprint).permit(:id, :description, :semester, :inicio, :fim,
                                  :pontos_cadastrados, :pontos_atualizados)
  end

  def verify_dates
    inicio_params = params[:sprint][:inicio]
    fim_params = params[:sprint][:fim]

    # Verification if exist any registry with same datas
    unless inicio_params.blank?
      if Sprint.where("(inicio <= ? AND fim >= ?)",
                      Date.parse(inicio_params),
                      Date.parse(inicio_params)).exists?
        @sprint.errors.add(:inicio, "é inválido. Já existe uma Sprint em andamento
                                     entre esse período de tempo (#{inicio_params}).")
      end

      if Sprint.where("(inicio >= ? AND fim >= ?) AND
                       (inicio <= ? AND fim <= ?)",
                      Date.parse(inicio_params),
                      Date.parse(inicio_params),
                      Date.parse(fim_params),
                      Date.parse(fim_params)).exists?
        @sprint.errors.add(:inicio, "é inválido. Já existe uma Sprint em andamento
                                     entre esse período de tempo (#{inicio_params}).")
        @sprint.errors.add(:fim, "é inválido. Já existe uma Sprint em andamento
                                  entre esse período de tempo (#{fim_params}).")
      end
    end

    if Sprint.where("(inicio <= ? AND fim >= ?)",
                    Date.parse(fim_params),
                    Date.parse(fim_params)).exists?
      @sprint.errors.add(:fim, "é inválido. Já existe uma Sprint em andamento
                                entre esse período de tempo (#{fim_params}).")
    end

  end

  def create_weeks_dynamically
    # Generate the Weeks dynamically
    start_s = @sprint.inicio
    end_s = @sprint.fim

    while(start_s < end_s)
      difference = start_s.wday == 1 ? 4 : 1.week - 1.day
      Week.create(
        description: Week.last.present? ?
                     "Semana #{Week.where(sprint_id: @sprint.id).count + 1}" :
                     "Semana 1",
        start_w: start_s,
        end_w: start_s + difference,
        expected_hours: 15,
        sprint_id: @sprint.id
        )
      start_s += 1.week
    end
  end

  def update_weeks_dynamically(last_end)
    # Generate the Weeks dynamically
    last_end_s = last_end
    new_end_s = @sprint.fim

    while(last_end_s < new_end_s)
      difference = last_end_s.wday == 1 ? 4 : 1.week - 1.day
      Week.create(
        description: "Semana #{Week.where(sprint_id: @sprint.id).count + 1}",
        start_w: last_end_s,
        end_w: last_end_s + difference,
        expected_hours: 15,
        sprint_id: @sprint.id
        )
      last_end_s += 1.week
    end
  end

end

app/helpers/sprints_helper.rb
module SprintsHelper

  def weeks_of_sprint(sprint)

    start_s = sprint.inicio
    end_s = sprint.fim
    weeks = []
    date = start_s

    while date <= end_s

      if weeks.blank? && date.beginning_of_week <= date &&
         date.end_of_week <= end_s
        weeks.push([date, date.end_of_week - 2])
        date = date.next_week
        next
      end

      if weeks.blank? && date.beginning_of_week < date &&
         date.end_of_week > end_s
        weeks.push([date, end_s])
        date = date.next_week
        next
      end

      if !weeks.blank? && date.end_of_week <= end_s
        weeks.push([date.beginning_of_week, date.end_of_week - 2])
        date = date.next_week
        next
      end

      if !weeks.blank? && date.end_of_week > end_s
        weeks.push([date.beginning_of_week, end_s])
        date = date.next_week
        next
      end
    end

    return weeks
  end
end

app/views/sprints/shared/_datepicker_call.html.erb
<script>
  $(document).ready(function(){
    $('.datepicker').datepicker({
      todayBtn: true,
      language: "pt-BR",
      todayHighlight: true,
      daysOfWeekDisabled: [0, 6]
    });
  });

  function setSprintFim(dateInput) {
    var value = dateInput; // "04/07/2017"
    // var d = new Date(2017, 06, 04)
    var d = new Date(value[6] + value[7] + value[8] + value[9],
                     parseInt(value[3] + value[4]) - 1,
                     value[0] + value[1]);
    var days = [0, 1, 2, 3, 4, 5, 6];
    delete days[days.indexOf(d.getDay() - 1)]; // Excluir todos os dias menos o dia anterior

    d.setDate(d.getDate() + 6);

    $('#sprint_fim').datepicker('destroy');
    $('#sprint_fim').datepicker({
      todayBtn: true,
      language: "pt-BR",
      todayHighlight: true,
      startDate: d.toLocaleDateString('pt-BR'),
      daysOfWeekDisabled: days
    });

    $('#sprint_fim').datepicker("setDate", d.toLocaleDateString('pt-BR'));
  }
</script>

app/views/sprints/shared/_index_adm.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Lista de Sprints</center></h3>
      </div>
    </div>

    <div class="panel-body">
      <table class="table table-striped table-hover ">

        <thead>
          <tr>
            <th><%= @sprints.model.human_attribute_name("Descrição") %></th>
            <th><%= @sprints.model.human_attribute_name("inicio") %></th>
            <th><%= @sprints.model.human_attribute_name("fim") %></th>
            <th><%= @sprints.model.human_attribute_name("pontos_cadastrados") %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @sprints.each do |sprint| %>
            <tr>
              <td><%= truncate(sprint.description, length: 20) %></td> <!-- trunca o tamanho para 10 -->
              <td><%= l(sprint.inicio) %></td> <!-- l=locale (traducao) -> traduz datas, palavras -->
              <td><%= l(sprint.fim) %></td>

              <% pontos_cadastrados = 0 %>
              <% sprint.activities.each do |activity| %>
                <% pontos_cadastrados += activity.pontos_cadastrados %>
              <% end %>

              <td><%= pontos_cadastrados %></td>

              <td width="100" align="center">
                <%= link_to "Visualizar", sprint_path(sprint) %>
              </td>

              <% if can? :update, Sprint %>
                <td width="100" align="center">
                  <%= link_to t('buttons.edit'), edit_sprint_path(sprint) %>
                </td>
              <% end %>

              <% if can? :destroy, Sprint %>
                <td width="100" align="center">
                  <%= link_to t('buttons.destroy'), sprint_path(sprint), method: :delete, data: { confirm: t('messages.confirm') } %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>

      </table>

      <center><%= paginate @sprints %></center>

      <% if can? :create, Sprint %>
        <%= link_to t('buttons.new'), new_sprint_path, class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/sprints/shared/_index_user.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Lista de Sprints</center></h3>
      </div>
    </div>

    <div class="panel-body">

        <% @projects.each do |project| %>

          <span class="title">Projeto: </span> <%= project.description %>
          <br>
          <span class="title">Equipe: </span> <%= project.team.description %>
          <br><br>
          <span class="title">Sprints:</span>

          <br><br>

          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Descrição</th>
                <th>Inicio</th>
                <th>Fim</th>
                <th>Pontos Cadastrados</th>
                <th width="150"></th>
              </tr>
            </thead>

            <tbody>
              <% project.sprints.each do |sprint| %>
                <tr>
                  <td><%= truncate(sprint.description, length: 20) %></td> <%# trunca o tamanho para 10 %>
                  <td><%= l(sprint.inicio) %></td> <%#l=locale (traducao) -> traduz datas, palavras %>
                  <td><%= l(sprint.fim) %></td>

                  <% pontos_cadastrados = 0 %>
                  <% sprint.activities.each do |activity| %>
                    <% if activity.project.id == project.id %>
                      <% pontos_cadastrados += activity.pontos_cadastrados %>
                    <% end %>
                  <% end %>

                  <td><%= pontos_cadastrados %></td>

                  <td align="center">
                    <%= link_to "Visualizar", sprint_path(sprint, project: project) %>
                  </td>

                </tr>
              <% end %>
            </tbody>
          </table>

          <% unless project == @projects.last %>
            <hr style="border-top-color: dimgray;"><br>
          <% end %>
        <% end %>

      <center><%= paginate @projects %></center>

    </div>
  </div>
</div>

app/views/sprints/shared/_show_adm.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Visualização da Sprint</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <span class="title">Descrição:</span> <%= @sprint.description %> <br>
      <span class="title">Inicio:</span> <%=  l(@sprint.inicio) %> <br>
      <span class="title">Fim:</span> <%=  l(@sprint.fim) %> <br>

      <br>
      <span class="title">Pontos cadastrados:</span> <br><br>

      <table class="table table-striped table-hover ">

        <thead>
          <tr>
            <th>Projeto</th>
            <th>Qtd. de atividades</th>
            <th>Pontos cadastrados</th>
            <th></th>
          </tr>
        </thead>

        <tbody>

          <% @sprint.projects.each do |project| %>

            <tr>

              <td>
                <%= truncate(project.description, length: 35) %>
              </td>

              <td>
                <!-- Imprime a quantidade de atividades desse projeto que fazem parte da sprint vizualizada -->
                <%= project.activities.where(sprint_id: @sprint).count %>
              </td>

              <td>
                <% pontos_cadastrados = 0 %>
                <% project.activities.where(sprint_id: @sprint).each do |activity| %>
                  <% pontos_cadastrados += activity.pontos_cadastrados %>
                <% end %>

                <%= pontos_cadastrados %>
              </td>

              <td width="70" align="center">
                <%= link_to "Visualizar", project_path(project) %>
              </td>

            </tr>

          <% end %>

        </tbody>

      </table>

      <span class="title">Pontos atualizados:</span> <%= @sprint.pontos_atualizados %>

      <br><br><br>

      <%= link_to t('buttons.edit'), edit_sprint_path(@sprint), class: "btn btn-primary" %> |

      <%= link_to t('buttons.back'), sprints_path, class: "btn btn-success" %>

    </div>

  </div>
</div>

app/views/sprints/shared/_show_user.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Visualização da Sprint</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <% unless current_user_total? %>
        <ul class="breadcrumb" style="background-color: #3e3b3b;">
          <li><%= link_to "Projeto", project_path(@project) %></li>
          <li class="active">Sprint</li>
        </ul>
      <% end %>

      <span class="title">Descrição:</span> <%= @sprint.description %> <br>
      <span class="title">Inicio:</span> <%=  l(@sprint.inicio) %> <br>
      <span class="title">Fim:</span> <%=  l(@sprint.fim) %> <br>

      <% pontos_cadastrados = 0 %>

      <% @sprint.activities.each do |activity| %>
        <% if activity.project.id == @project.id %>
          <% pontos_cadastrados += activity.pontos_cadastrados %>
        <% end %>
      <% end %>

      <span class="title">Pontos cadastrados:</span> <%=  pontos_cadastrados %> <br>

      <span class="title">Pontos atualizados:</span> <%= @sprint.pontos_atualizados %>

      <hr style="border-top-color: dimgray;">
      <span class="title">Atividades:</span> <br><br>

      <table class="table table-striped table-hover ">

        <thead>
          <tr>
            <th>Descrição</th>
            <th>Pontos cadastrados</th>
            <th>Status</th>
            <th>Rótulo</th>
            <th>Projeto</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @sprint.activities.each do |activity| %>
            <% if activity.project.id == @project.id %>
              <tr>
                <td>
                  <%= truncate(activity.description, length: 25) %>
                </td>
                <td>
                  <%= activity.pontos_cadastrados %>
                </td>
                <td>
                  <%= activity.status.blank? ? '-' : activity.status.description %>
                </td>
                <td>
                  <%= activity.label.blank? ? '-' : activity.label.description %>
                </td>
                <td>
                  <%= activity.project.description %>
                </td>

                <td width="70" align="center">
                  <%= link_to "Visualizar", activity_path(activity, project: @project, sprint: @sprint) %>
                </td>

                <% if can? :update, Activity %>
                  <td width="70" align="center">
                    <%= link_to t('buttons.edit'), edit_activity_path(activity) %>
                  </td>
                <% end %>

                <% if can? :destroy, Activity %>
                  <td width="70" align="center">
                    <%= link_to t('buttons.destroy'), activity_path, method: :delete, data: { confirm: t('messages.confirm') } %>
                  </td>
                <% end %>
              <% end %>

            </tr>
          <% end %>
        </tbody>

      </table>

      <% unless current_user_total? %>
        <%= link_to t('buttons.new'), new_activity_path(project: @project.id, sprint: @sprint.id), class: "btn btn-primary" %>
      <% end %>

      <br><br><br><br>

      <% if can? :update, Sprint %>
        <%= link_to t('buttons.edit'), edit_sprint_path(@sprint), class: "btn btn-primary" %> |
      <% end %>

      <%= link_to t('buttons.back'), project_path(@project), class: "btn btn-success" %>

    </div>

  </div>
</div>