config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :user_profile

  resources :projects
  resources :sprints, except: [:index]
  resources :activities, except: [:index]
  resources :colors, except: [:show]
  resources :labels, except: [:show]
  resources :statuses, except: [:show]
  resources :macro_activities, except: [:index, :show]
  resources :progresses, except: [:show]
  get '/progresses/report_pdf', to: 'progresses#report_pdf', as: 'progress_report_pdf'
  resources :weeks, only: [:edit, :update]

  post '/projects/:id/login', to: 'hours_registries#login', as: 'project_login'
  put '/projects/:id/logout', to: 'hours_registries#logout', as: 'project_logout'

  get 'progresses/graphic' => 'progresses#graphic'

  post 'team_users/edit_multiple'
  put 'team_users/update_multiple'

  get 'home/index'
  root 'home#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

  # Associations
  belongs_to :team

  has_many :activities, dependent: :destroy
  has_many :project_sprints, dependent: :destroy
  has_many :sprints, through: :project_sprints

  has_many :macro_activities, dependent: :destroy
  has_many :progresses, dependent: :destroy

  has_many :hours_registries, dependent: :destroy


  # Validations
  validates_presence_of :description, :team_id

  # Nested Attributes
  accepts_nested_attributes_for :progresses, allow_destroy: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # Erro da gem Cancan (ActiveModel::ForbiddenAttributesError)
  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  load_and_authorize_resource

  def index
    if current_user_total?
      @projects = Project.all.order(:description).page(params[:page]).per(10)
    else
      ids = []
      tus = TeamUser.where(user_id: current_user.id)
      tus.each do |tu|
        ids << tu.team_id
      end

      @projects = Project.where(team_id: ids).order(:description)
                  .page(params[:page]).per(10)
    end
  end

  def show
    @project = Project.find(params[:id])
    @sprints = @project.sprints
  end

   def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save

      @sprints = Sprint.where(id: params[:sprint_ids])

      if @sprints.present?
        @sprints.each do |sprint|
          project_sprint = ProjectSprint.new
          project_sprint.project_id = @project.id
          project_sprint.sprint_id = sprint.id
          project_sprint.save
        end
      end

      redirect_to project_path(@project), notice: "Projeto criado com sucesso!"

    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @sprints = Sprint.where(id: params[:sprint_ids]).ids

    # Atualização das sprints do projeto [ProjectSprint]
    @project.project_sprints.each do |project_sprint|
      @id = @sprints.sample

      if @id.blank?
        project_sprint.destroy
      else
        project_sprint.update_attribute('sprint_id', @id)
      end
      @sprints.delete(@id)
    end

    unless @sprints.blank?
      @sprints.each do |sprint|
        ProjectSprint.create!(
          project_id: @project.id,
          sprint_id: sprint
          )
      end
    end

    # Atualização dos progressos do projeto
    @project.progresses.each do |p|
      p.advance = @project.progresses.where('id < ?', p.id).present? ?
                  p.completeness.to_i - @project.progresses
                                        .where('id < ?', p.id).last
                                        .completeness.to_i :
                  p.completeness
      p.save!
    end

    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Projeto atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path, notice: "Projeto deletado com sucesso!"
    else
      redirect_to projects_path, notice: "Erro ao deletar o Project..."
    end
  end

  private

  def project_params
    params.require(:project).permit(:id, :description, :team_id,
                                    progresses_attributes:
                                    [:id, :completeness, :advance,
                                     :_destroy])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<br/>
<%= form_for(@project, html: { class: "basic-grey" }) do |f| %>

  <h1>
    Novo Projeto
  </h1>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <label>Equipe</label>
    <%= f.select(:team_id,
                 Team.all.collect {|t| [ t.description, t.id ] },
                 {selected: @project.team_id}) %>

  </div>

  <label>Sprint(s)</label>
  <% for sprint in @project.sprints %>
    <div class="field">
      <%= hidden_field_tag  "sprint_ids[]", sprint.id %>
      <%= f.select("sprint_ids[]",
                 Sprint.all.collect {|s| [ truncate(s.description, length: 55), s.id ] },
                 {selected: sprint.id},
                 {onchange: 'sprint_ids(this)'}) %>
      <a href="#" class="btn btn-default" onclick="removeSelect(this)">Remover</a>
      <br>
    </div>
  <% end %>

  <span id="add"></span>

  <a href="#" class="btn btn-default" onclick="addSelect(this)">Adicionar</a>

  <br><br>

  <div class="field">
    <%= f.submit t('buttons.save'), class: "btn btn-primary" %>
    <%= link_to t('buttons.back'), project_path(@project), class: "btn btn-success"%>
  </div>

<% end %>

<script>
  function sprint_ids(select){
    var selectedIndex = select.options.selectedIndex;
    var value = select.options[selectedIndex].value;
    var hidden_field = select.closest('div.field').firstElementChild;
    hidden_field.value = value;
  };

  function removeSelect(link){
    var div = link.closest('div.field');

    confirm('Tem certeza?') ? div.remove() : "";
  };

  function addSelect(link){
    $('#add').replaceWith("<%= j (render ('select_sprints')) %>");
  };
</script>

app/views/projects/_select_sprints.html.erb
<div class="form-group">
  <%= hidden_field_tag  "sprint_ids[]" %>

  <div class="col-lg-6 col-lg-offset-2">
    <%= select(nil, "sprint_ids[]",
               Sprint.all.collect {|s| [ truncate(s.description, length: 55), s.id ] },
               {include_blank: '-- Selecione um sprint --'},
               {onchange: 'sprint_ids(this)', class: "form-control"}) %>
  </div>

  <div class="col-lg-2">
    <a onclick='removeSelect(this)' class="btn btn-default">Remover</a>
  </div>

</div>

<span id="add"></span>

app/views/projects/edit.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Editar projeto</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <%= form_for(@project, html: { class: 'form-horizontal' }) do |f| %>

        <% if @project.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-dismissible alert-danger">
              <p>
                <h5> Existe(m) <%= @project.errors.count %> erro(s) no formulário:</h5>
              </p>
              <ul>
                <% @project.errors.full_messages.each do |message| %>
                    <li><h6><%= message %></h6></li>
                <% end %>
              </ul>
            </div>
          </div>
          <br>
        <% end %>

        <fieldset>

          <div class="form-group">
            <label class="col-lg-3 control-label">Descrição: </label>
            <div class="col-lg-7">
              <%= f.text_field :description, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-lg-3 control-label">Equipe: </label>
            <div class="col-lg-7">
              <%= f.select(:team_id,
                           Team.all.collect {|t| [ t.description, t.id ] },
                           {selected: @project.team_id},
                           {class: 'form-control'}) %>
            </div>
          </div>

          <div class="form-group">
            <hr>
            <h5 class=" col-lg-2 col-lg-offset-2">Sprint(s)</h5>
          </div>

          <% for sprint in @project.sprints %>

            <div class="form-group">
              <%= hidden_field_tag  "sprint_ids[]", sprint.id %>

              <div class="col-lg-6 col-lg-offset-2">
                <%= f.select("sprint_ids[]",
                        Sprint.all.collect {|s| [ truncate(s.description, length: 55), s.id ] },
                        {selected: sprint.id},
                        {onchange: 'sprint_ids(this)', class: 'form-control'}) %>
              </div>

              <div class="col-lg-2">
                <a class="btn btn-default" onclick="removeSelect(this)">
                  Remover
                </a>
              </div>

            </div>

          <% end %>

          <span id="add"></span>


          <br>
          <div class="form-group">
            <div class="col-lg-2 col-lg-offset-2">
              <a class="btn btn-default" onclick="addSelect()">Adicionar</a>
            </div>
          </div>

          <br>

          <div class="col-lg-7">
            <%= f.submit t('buttons.save'), class: "btn btn-primary" %> |
            <%= link_to t('buttons.back'), project_path(@project), class: "btn btn-success"%>
          </div>

        </fieldset>
      <% end %>

    </div>
  </div>
</div>

<script>
  function sprint_ids(select){
    var selectedIndex = select.options.selectedIndex;
    var value = select.options[selectedIndex].value;
    var hidden_field = select.closest('div.form-group').firstElementChild;
    hidden_field.value = value;
  };

  function removeSelect(link){
    var div = link.closest('div.form-group');

    confirm('Tem certeza?') ? div.remove() : "";
    // div.remove();
  };

  function addSelect(link){
    $('#add').replaceWith("<%= j (render partial: ('projects/shared/select_sprints')) %>");
  };
</script>

app/views/projects/index.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Lista de projetos</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <br>

      <table class="table table-striped table-hover ">

        <thead>
          <tr>

            <th><center>Descrição</center></th>

            <th><center>Equipe</center></th>

            <th><center>Qtd. Sprints</center></th>

            <th colspan="4"></th>

          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>

              <td align="center">
                <%= truncate(project.description, length: 20) %>
              </td>

              <td align="center">
                <%= project.team.description %>
              </td>

              <td align="center">
                <!-- Aparecer a quantidade exata de sprints no projeto, sem filtros -->
                <%= project.sprints.count %>
              </td>

              <% unless current_user_total? %>

                <%# VERIFICA SE EXISTE ALGUMA SPRINT EM ANDAMENTO %>
                <% if project.sprints.where('inicio <= ? AND fim >= ?',
                                            Date.today, Date.today).present? %>

                  <%# RECUPERA A SEMANA CORRENTE DA SPRINT EM ANDAMENTO %>
                  <% w_id = project.sprints.where('inicio <= ? AND fim >= ?', Date.today, Date.today).first.weeks.where('start_w <= ? AND end_w >= ?',Date.today, Date.today).first.id %>

                  <%# VERIFICA SE EXISTE ALGUM REGISTRO DE HORA NESSA SEMANA
                      DESSE USUÁRIO %>
                  <% if HoursRegistry.where(
                       user_id: current_user.id,
                       week_id: w_id,
                       project_id: project.id
                       ).present? %>

                    <%# VERIFICA SE O REGISTRO DE HORA ESTÁ COM O INÍCIO EM
                        BRANCO %>
                    <% if HoursRegistry.where(
                         user_id: current_user.id,
                         week_id: w_id,
                         project_id: project.id
                         ).first.start_hr.blank? %>

                      <%# SE SIM, IMPRIME O LOGAR %>
                      <td width="100" align="center">
                        <%= link_to "Logar", project_login_path(project, week: w_id), method: 'post' %>
                      </td>

                    <% else %>

                      <%# SE NÃO, IMPRIME O DESLOGAR %>
                      <td width="100" align="center">
                        <%= link_to "Deslogar", project_logout_path(project, week: w_id), method: 'put' %>
                      </td>

                    <% end %>

                  <% else %>

                    <%# SE NÃO, IMPRIME O LOGAR %>
                    <td width="100" align="center">
                      <%= link_to "Logar", project_login_path(project, week: w_id), method: 'post' %>
                    </td>

                  <% end %>

                <% else %>

                  <%# SE NÃO, IMPRIME O LOGAR 'NÃO PERMITIDO' %>
                  <td width="100" align="center">
                    <a style="cursor: not-allowed;">Logar</a>
                  </td>

                <% end %>

              <% end %> <%# / UNLESS CURRENT_USER_TOTAL?  %>

              <td width="100" align="center">
                <%= link_to "Visualizar", project_path(project) %>
              </td>

              <% if can? :update, Project %>
                <td width="100" align="center">
                  <%= link_to t('buttons.edit'), edit_project_path(project) %>
                </td>
              <% end %>

              <% if can? :destroy, Project %>
                <td width="100" align="center">
                  <%= link_to t('buttons.destroy'), project_path(project), method: :delete, data: { confirm: t('messages.confirm') } %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>

      </table>

      <center><%= paginate @projects %></center>

      <% if can? :create, Project %>
        <%= link_to t('buttons.new'), new_project_path, class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Criar projeto</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <%= form_for(@project, html: { class: 'form-horizontal' }) do |f| %>

        <% if @project.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-dismissible alert-danger">
              <p>
                <h5> Existe(m) <%= @project.errors.count %> erro(s) no formulário:</h5>
              </p>
              <ul>
                <% @project.errors.full_messages.each do |message| %>
                    <li><h6><%= message %></h6></li>
                <% end %>
              </ul>
            </div>
          </div>
          <br>
        <% end %>

        <fieldset>

          <div class="form-group">
            <label class="col-lg-3 control-label">Descrição: </label>
            <div class="col-lg-7">
              <%= f.text_field :description, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-lg-3 control-label">Equipe: </label>
            <div class="col-lg-7">
              <%= f.select(:team_id,
                           Team.all.collect {|t| [ t.description, t.id ] },
                           {},
                           {class: 'form-control'}) %>
            </div>
          </div>

          <div class="form-group">
            <hr>
            <h5 class=" col-lg-2 col-lg-offset-2">Sprint(s)</h5>
          </div>

          <div class="form-group">
            <%= hidden_field_tag  "sprint_ids[]" %>

            <div class="col-lg-6 col-lg-offset-2">
              <%= f.select("sprint_ids",
                         Sprint.all.collect {|s| [ truncate(s.description, length: 55), s.id ] },
                         {include_blank: '-- Selecione um sprint --'},
                         {onchange: 'sprint_ids(this)', class: "form-control"}) %>
            </div>

            <div class="col-lg-2">
              <a onclick='removeSelect(this)' class="btn btn-default">Remover</a>
            </div>

          </div>

          <span id="add"></span>


          <br>
          <div class="form-group">
            <div class="col-lg-2 col-lg-offset-2">
              <a class="btn btn-default" onclick="addSelect(this)">Adicionar</a>
            </div>
          </div>

          <br>

          <div class="col-lg-7">
            <%= f.submit t('buttons.save'), class: "btn btn-primary" %> |
            <%= link_to t('buttons.back'), projects_path, class: "btn btn-success"%>
          </div>

        </fieldset>
      <% end %>

    </div>
  </div>
</div>

<script>
  function sprint_ids(select){
    var selectedIndex = select.options.selectedIndex;
    var value = select.options[selectedIndex].value;
    var hidden_field = select.closest('div.form-group').firstElementChild;
    hidden_field.value = value;
  };

  function removeSelect(link){
    var div = link.closest('div.form-group');

    confirm('Tem certeza?') ? div.remove() : "";
    // div.remove();
  };

  function addSelect(link){
    $('#add').replaceWith("<%= j (render partial: ('projects/shared/select_sprints')) %>");
  };
</script>

app/views/projects/show.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Visualização do Projeto</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <ul class="breadcrumb">
        <div class="row">

          <div class="col-lg-5 col-sm-5">
            <li><%= link_to "Projetos", projects_path %></li>
          </div>

          <%= render partial: 'progresses/shared/progress_bar' %>

          <%= render partial: 'progresses/shared/dropdown_progresses' %>

        </div>
      </ul>

      <div class="row">
        <div class="col-lg-6 lg-sm-6">
          <div class="pull-left">
            <span class="title">Descrição:</span> <%= @project.description %> <br>
            <span class="title">Equipe:</span> <%= @project.team.description %> <br>
          </div>
        </div>


        <div class="col-lg-6 lg-sm-6">
          <div class="pull-right">
          </div>
        </div>
      </div>

      <%= render partial: 'projects/shared/sprints_list' %> <br><br>

      <%= render partial: 'projects/shared/macro_activities_list' %>

      <br><br>


      <% if can? :update, Project %>
        <td width="100" align="center">
          <%= link_to t('buttons.edit'), edit_project_path(@project), class: "btn btn-primary" %> |
        </td>
      <% end %>

      <%= link_to t('buttons.back'), projects_path, class: "btn btn-success" %>

    </div>

  </div>
</div>